CHK-974-added-mock-for-ecommerce-service
pagopa/pagopa-checkout-be-mock pull request #25
Opened 2023-01-18 13:55 UTC by Fernando-Granato

#### List of Changes

Added in the package.json the generation of the code related to the ecommerce project.
Added new methods for integrating checkout-fe with ecommerce.
**-  GET /checkout/ecommerce/v1/payment-methods/psps**
**-  GET /checkout/ecommerce/v1/payment-methods/:id/psps**
**-  GET /checkout/ecommerce/v1/transactions/:transactionId** 
**-  POST /checkout/ecommerce/v1/transactions**

![Screenshot 2023-01-23 alle 10 18 28](https://user-images.githubusercontent.com/117268775/214003998-f2a0bb0c-0a4d-49f3-bb49-c63a7783ed00.png)

**-  POST /checkout/ecommerce/v1/transactions/:transactionId/auth-requests** 
 
![Screenshot 2023-01-23 alle 10 18 34](https://user-images.githubusercontent.com/117268775/214004039-10a6f430-71f3-416f-89f9-10ed6b100e51.png)

Modified old ecommerce endpoints using generated ecommerce code.
#### Motivation and Context

The change was made to allow checkout-fe to integrate with ecommerce
#### How Has This Been Tested?

The tests were performed locally.

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-01-20 14:16 UTC, giovanniberti reviewed
You have implemented authorization flows in terms of the transaction id.
How should the frontend drive the mock in this way? If I understand the frontend should set a custom transaction id when asking for an authorization request to exercise the different cases

2023-01-20 14:16 UTC, giovanniberti commented on src/flow.ts
> +    E.toUnion
Be aware that functions like `toUnion` are to be used with **extreme care**, as they bypass almost completely every form of type checking. As a rule of thumb, if you have to use them you're 99% sure doing something wrong or not specifying enough type information to the compiler 🙂.

Here you're exploiting the fact that `toUnion` returns `E | A` and here you have `A  = E = AuthRequestFlowCase` so that the function's return type is `AuthRequestFlowCase | AuthRequestFlowCase = AuthRequestFlowCase`, but this usage  can be (more safely) be expressed as:

```typescript
pipe(
  transactionId,
  E.fromPredicate(
    id =>
      id.startsWith(AUTH_REQUEST_TRANSACTION_SUCCESSFULLY_PROCESSED_PREFIX),
    identity
  ),
  E.mapLeft(_ => AuthRequestFlowCase.TRANSACTION_ID_NOT_FOUND),
  E.chain(id =>
    pipe(
      id,
      E.fromPredicate(
        reqId =>
          reqId.startsWith(
            AUTH_REQUEST_ALREADY_PROCESSED_TRANSACTION_ID_PREFIX
          ),
        identity
      ),
      E.mapLeft(_ => AuthRequestFlowCase.TRANSACTION_SUCCESSFULLY_PROCESSED),
      E.map(_ => AuthRequestFlowCase.TRANSACTION_ID_ALREADY_PROCESSED)
    )
  ),
  E.fold(identity, identity)
);
```

The same logic (modulo human error on my part 🙂) can be further refactored into:
```typescript
export const getAuthRequestFlowCase = (
  transactionId: string
): AuthRequestFlowCase =>
  pipe(
    transactionId,
    E.fromPredicate(
      id =>
        id.startsWith(AUTH_REQUEST_TRANSACTION_SUCCESSFULLY_PROCESSED_PREFIX),
      _ => AuthRequestFlowCase.TRANSACTION_ID_NOT_FOUND
    ),
    E.filterOrElse(
      id => id.startsWith(AUTH_REQUEST_ALREADY_PROCESSED_TRANSACTION_ID_PREFIX),
      _ => AuthRequestFlowCase.TRANSACTION_ID_NOT_FOUND
    ),
    E.fold(
      _ => AuthRequestFlowCase.TRANSACTION_SUCCESSFULLY_PROCESSED,
      _ => AuthRequestFlowCase.TRANSACTION_ID_ALREADY_PROCESSED
    )
  );
```

Now, given that `AUTH_REQUEST_TRANSACTION_SUCCESSFULLY_PROCESSED_PREFIX` is a prefix of `AUTH_REQUEST_ALREADY_PROCESSED_TRANSACTION_ID_PREFIX`, can't this be simplified to:
```typescript
export const getAuthRequestFlowCase = (
  transactionId: string
): AuthRequestFlowCase =>
  pipe(
    transactionId,
    E.filterOrElse(
      id => id.startsWith(AUTH_REQUEST_ALREADY_PROCESSED_TRANSACTION_ID_PREFIX),
      _ => AuthRequestFlowCase.TRANSACTION_ID_NOT_FOUND
    ),
    E.fold(
      _ => AuthRequestFlowCase.TRANSACTION_SUCCESSFULLY_PROCESSED,
      _ => AuthRequestFlowCase.TRANSACTION_ID_ALREADY_PROCESSED
    )
  );
```
?

2023-01-20 14:24 UTC, Fernando-Granato commented on package.json
> +    "generate:ts-from-yaml:api": "shx mkdir -p src/generated/payment_manager && shx mkdir -p src/generated/pagopa_proxy && rimraf src/generated/payment_manager/* && rimraf src/generated/pagopa_proxy/
Fixed

2023-01-20 14:50 UTC, Fernando-Granato commented
> You have implemented authorization flows in terms of the transaction id. How should the frontend drive the mock in this way? If I understand the frontend should set a custom transaction id when asking for an authorization request to exercise the different cases

I could handle multiple success cases during activation phase (based on different rptId) by returning different transactionIDs to handle error cases during auth-request phase what do you think ?

2023-01-23 09:23 UTC, Fernando-Granato commented on src/flow.ts
> +    E.toUnion
I think you are right 🙂.
Although I realized that by using the cookie to simulate error streams this written code can be deleted. 
Thanks for the tip 🚀

2023-01-26 10:45 UTC, giovanniberti commented on README.md
> +| FAIL_AUTH_REQUEST_TRANSACTION_ID_ALREADY_PROCESSED | 409 transaction already processed     |
Update docs :)

2023-01-26 10:58 UTC, giovanniberti commented on README.md
> +| FAIL_AUTH_REQUEST_TRANSACTION_ID_ALREADY_PROCESSED | 409 transaction already processed     |
Solved in [`c6d3089`](https://github.com/pagopa/pagopa-checkout-be-mock/pull/25/commits/c6d308975225ee9422527e05d74e09f0436e730c)

2023-01-26 10:58 UTC, giovanniberti approved these changes

2023-01-26 10:59 UTC, giovanniberti reviewed
.

2023-01-26 10:59 UTC, giovanniberti requested changes
.

2023-01-26 11:11 UTC, giovanniberti approved these changes

2023-01-26 14:29 UTC, merged